name: build
on: [push, pull_request]
jobs:
  kustomize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ "kind", "test", "prod" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Kustomize
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          kustomize: 3.5.5
          command: |
            kustomize build ./${{ matrix.cluster }}/ --output ./build.${{ matrix.cluster }}.yaml
